### ISSUE TITLE
Investigate the feasibility of OAuth2 for API authentication

### ISSUE THREAD

**Issue by funpdbe** [funpdbe-consortium/funpdbe-deposition#4]
Will have to decide whether OAuth2 is the right way of handling authentication when giving access to partners to deposit via the API.
Django has a package for this, django-oauth-toolkit, which works well with djangorestframework too.

**Comment by mvaradi** [comment]
We won't be using OAuth2 as it would be overkill for this particular application. Simple user/password authentication will suffice, especially since "users" will be resources, not persons
