### ISSUE TITLE
Getting domain names

### ISSUE THREAD

**Issue by funpdbe** [funpdbe-consortium/funpdbe-deposition#9]
We need to register domain names for the FunPDBe front-end.
Domains required:
* funpdbe.org
* funpdb.org
* funpdbe.eu
* funpdb.eu

**Comment by funpdbe** [comment]
We have funpdbe.org and funpdb.org, purchased and registered by EBI. As UK based institute, we couldn't get .eu domains, because UK is not considered to be part of the EU for this purpose. Will have to ask EMBL Germany if they can handle this for us.

**Comment by mvaradi** [comment]
Got the domain names
